# SETUPFILE: https://raw.githubusercontent.com/fniessen/org-html-themes/master/org/theme-readtheorg.setup
# SETUPFILE: https://raw.githubusercontent.com/mkronvold/mkronvold.github.io/main/theme-readtheorg.setup
# Unset body width limit of ReadTheOrg
# HTML_HEAD: <style> #content{max-width:1800px;}</style>
# HTML_HEAD: <style> p{max-width:800px;}</style>
# HTML_HEAD: <style> li{max-width:800px;}</style

# SETUPFILE: https://raw.githubusercontent.com/fniessen/org-html-themes/master/org/theme-bigblow.setup

# SETUPFILE: https://gitlab.com/OlMon/org-themes/-/raw/master/src/darksun/export/setup/theme-darksun.setup
#+SETUPFILE: export/setup/theme-darksun-local.setup
